// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.UsernameRegistry
{
    public partial class UsernameRegistryModule_UsernameResult
    {
        public bool Success;
        public string Username;
        public string Error;

        [Preserve]
        public UsernameRegistryModule_UsernameResult ()
        {
        }
    }
}