// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class UsernameRegistryModuleBindings
    {
        readonly ICloudCodeService k_Service;

        public UsernameRegistryModuleBindings() : this(CloudCodeService.Instance) { }

        public UsernameRegistryModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<UsernameRegistry.UsernameRegistryModule_UsernameResult> ClaimUsername(string requestedName)
        {
            return await k_Service.CallModuleEndpointAsync<UsernameRegistry.UsernameRegistryModule_UsernameResult>(
                "UsernameRegistry",
                "ClaimUsername",
                new Dictionary<string, object>()
                {
                    {"requestedName", requestedName},
                });
        }

        public async Task<bool> IsUsernameAvailable(string requestedName)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "UsernameRegistry",
                "IsUsernameAvailable",
                new Dictionary<string, object>()
                {
                    {"requestedName", requestedName},
                });
        }

        public async Task<bool> ReleaseUsername()
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "UsernameRegistry",
                "ReleaseUsername",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<bool> RemoveUsername(string requestedName)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "UsernameRegistry",
                "RemoveUsername",
                new Dictionary<string, object>()
                {
                    {"requestedName", requestedName},
                });
        }

        public async Task<string> GetUsername(string playerId)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UsernameRegistry",
                "GetUsername",
                new Dictionary<string, object>()
                {
                    {"playerId", playerId},
                });
        }

        public async Task InitializeRegistry()
        {
            await k_Service.CallModuleEndpointAsync(
                "UsernameRegistry",
                "InitializeRegistry",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
